### ISSUE TITLE
关于ruoyi脚手架其他功能的开发

### ISSUE THREAD

**Issue by yangbailan** [lyqgit/salvo-admin#10]
作者您好，是否有计划补全ruoyi脚手架其他功能的研发呢。

参数管理：对系统动态配置常用参数。
通知公告：系统通知公告信息发布维护。
操作日志：系统正常操作日志记录和查询；系统异常信息日志记录和查询。
登录日志：系统登录日志记录查询包含登录异常。
在线用户：当前系统中活跃用户状态监控。
定时任务：在线（添加、修改、删除)任务调度包含执行结果日志。
代码生成：前后端代码的生成（java、html、xml、sql)支持CRUD下载 。
系统接口：根据业务代码自动生成相关的api接口文档。
服务监控：监视当前系统CPU、内存、磁盘、堆栈等相关信息。
缓存监控：对系统的缓存查询，查看、清理等操作。
在线构建器：拖动表单元素生成相应的HTML代码。
连接池监视：监视当期系统数据库连接池状态，可进行分析SQL找出系统性能瓶颈。

**Comment by lyqgit** [comment]
没有具体计划补全其他功能，目前有些功能缺少第三方库的支持，后续依然会更新一些新功能（比如在线多人协同excel在逐步完善），原本带的一些功能看情况研发
