### ISSUE TITLE
版本依赖报错？

### ISSUE THREAD

**Issue by huangjie0515** [lyqgit/salvo-admin#3]
windows11下cargo run运行报错, 当前环境rustup 1.26.0,cargo 1.73.0-nightly (d78bbf4bd 2023-08-03).

error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`
   --> D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\proc-macro2-1.0.56\src\wrapper.rs:475:33
    |
475 |                 let proc_macro::LineColumn { line, column } = s.start();
    |                                 ^^^^^^^^^^ not found in `proc_macro`
    |
help: consider importing this struct through its public re-export
    |
1   + use crate::LineColumn;
    |
help: if you import `LineColumn`, refer to it directly
    |
475 -                 let proc_macro::LineColumn { line, column } = s.start();
475 +                 let LineColumn { line, column } = s.start();
    |

**Comment by lyqgit** [comment]
可以切换到稳定版试试，cargo 1.71.1 运行没有问题

**Comment by huangjie0515** [comment]
你的是windows版本吗，依赖版本号都没有改动吗

**Comment by lyqgit** [comment]
我这块是Windows 10 专业版，依赖版本只更新了salvo的版本

**Comment by huangjie0515** [comment]
感谢，切换到stable，确实好了
