### ISSUE TITLE
目前发现的已知BUG

### ISSUE THREAD

**Issue by sunkaifei** [lyqgit/salvo-admin#4]
1.验证码：验证码验证是否相等时，应将服务端和用户端验证码都变成小写后再对比；
2. swagger-ui：应该后台登录后查看，不然目前页面是暴露的，不利于服务器安全；
3. 添加数据时都没有做去重查询，都可以反复加一样的数据，比如用户登录名；
4. 添加用户时如果不选所属部门，该用户就会查询不到，因为查询的时候会带组织id，该用户组织id为null了，所以查询不到了。

**Comment by lyqgit** [comment]
1、3、4问题修复已更新

**Comment by lyqgit** [comment]
swagger-ui加入了账号密码验证，登录成功后才可以查看
