### ISSUE TITLE
我用验证码登录时，报下面这个错

### ISSUE THREAD

**Issue by huangjie0515** [lyqgit/salvo-admin#6]
thread 'tokio-runtime-worker' panicked at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\fastdate-0.1.38\src\datetime.rs:672:22:
attempt to subtract with overflow
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\std\src\panicking.rs:597
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:127
   3: fastdate::datetime::DateTime::from_system_time
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\fastdate-0.1.38\src\datetime.rs:672
   4: fastdate::datetime::impl$6::from
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\fastdate-0.1.38\src\datetime.rs:401
   5: fastdate::datetime::DateTime::utc
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\fastdate-0.1.38\src\datetime.rs:50
   6: rbdc::types::datetime::DateTime::utc
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbdc-4.3.3\src\types\datetime.rs:89
   7: rbatis::plugin::snowflake::Snowflake::get_time
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\plugin\snowflake.rs:127
   8: rbatis::plugin::snowflake::Snowflake::generate
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\plugin\snowflake.rs:108
   9: rbatis::plugin::snowflake::new_snowflake_id
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\plugin\snowflake.rs:135
  10: rbatis::executor::impl$3::query::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\executor.rs:120
  11: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,en
um2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > > > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  12: rbatis::executor::impl$2::query::async_fn$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\executor.rs:54
  13: rbatis::executor::impl$22::query::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\executor.rs:532
  14: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,en
um2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > > > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  15: salvo_admin::mapper::user_mapper::impl$9::select_user_by_up::async_fn$0::select_user_by_up::async_fn$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\crud.rs:140  
  16: salvo_admin::mapper::user_mapper::impl$9::select_user_by_up::async_fn$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\rbatis-4.3.0\src\crud.rs:148  
  17: salvo_admin::service::user_service::get_user_by_up::async_fn$0
             at .\src\service\user_service.rs:16
  18: salvo_admin::controller::user_controller::impl$3::login::async_fn$0
             at .\src\controller\user_controller.rs:52
  19: salvo_admin::controller::user_controller::impl$5::handle::async_block$0
             at .\src\controller\user_controller.rs:37
  20: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  21: salvo_core::routing::impl$1::call_next::async_fn$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\routing\mod.rs:179
  22: core::panic::unwind_safe::impl$26::poll<enum2$<salvo_core::routing::impl$1::call_next::async_fn_env$0> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\panic\unwind_safe.rs:296    
  23: futures_util::future::future::catch_unwind::impl$1::poll::closure$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<salvo_core::routing::impl$1::call_next::async_fn_env$0> > >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\futures-util-0.3.28\src\future\future\catch_unwind.rs:36
  24: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<bool> >,futures_util::future
::future::catch_unwind::impl$1::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<salvo_core::routing::impl$1::call_next::async_fn_e
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\panic\unwind_safe.rs:271    
  25: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<futures_util::future::future::c
atch_unwind::impl$1::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<salvo_core::routing::impl$1::call_next::async_fn_env$0> > > >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panicking.rs:504
  26: hashbrown::raw::sse2::Group::match_byte
  27: std::panicking::try<enum2$<core::task::poll::Poll<bool> >,core::panic::unwind_safe::AssertUnwindSafe<fu
tures_util::future::future::catch_unwind::impl$1::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<salvo_core::routing::impl$1::cal
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panicking.rs:468
  28: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<futures_util::future::future::catch
_unwind::impl$1::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<salvo_core::routing::impl$1::call_next::async_fn_env$0> > > >,enu
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panic.rs:142
  29: futures_util::future::future::catch_unwind::impl$1::poll<core::panic::unwind_safe::AssertUnwindSafe<enum2$<salvo_core::routing::impl$1::call_next::async_fn_env$0> > >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\futures-util-0.3.28\src\future\future\catch_unwind.rs:36
  30: salvo_extra::catch_panic::impl$3::handle::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_extra-0.58.3\src\catch_panic.rs:26
  31: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  32: salvo_core::routing::impl$1::call_next::async_fn$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\routing\mod.rs:179
  33: salvo_extra::logging::impl$3::handle::async_block$0::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_extra-0.58.3\src\logging.rs:36
  34: tracing::instrument::impl$0::poll<enum2$<salvo_extra::logging::impl$3::handle::async_block$0::async_block_env$0> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tracing-0.1.37\src\instrument.rs:272
  35: salvo_extra::logging::impl$3::handle::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_extra-0.58.3\src\logging.rs:47
  36: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  37: salvo_core::routing::impl$1::call_next::async_fn$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\routing\mod.rs:179
  38: salvo_core::service::impl$2::handle::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\service.rs:174
  39: salvo_core::service::impl$3::call::async_block$3<hyper::body::incoming::Incoming>
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\service.rs:292
  40: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,en
um2$<core::result::Result<http::response::Response<enum2$<salvo_core::http::body::res::ResBody> >,hyper::error::Error> > > >,core::marker::Send>,alloc::
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  41: hyper::proto::h1::dispatch::impl$6::poll_msg<salvo_core::service::HyperHandler,enum2$<salvo_core::http::body::res::ResBody> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\proto\h1\dispatch.rs:505
  42: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<salvo_core::service::HyperHan
dler,hyper::body::incoming::Incoming>,enum2$<salvo_core::http::body::res::ResBody>,salvo_utils::rt::tokio_io::TokioIo<enum2$<tokio_util::either::Either<
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\proto\h1\dispatch.rs:309
  43: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<salvo_core::service::HyperHan
dler,hyper::body::incoming::Incoming>,enum2$<salvo_core::http::body::res::ResBody>,salvo_utils::rt::tokio_io::TokioIo<enum2$<tokio_util::either::Either<
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\proto\h1\dispatch.rs:168
  44: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<salvo_core::service::HyperHan
dler,hyper::body::incoming::Incoming>,enum2$<salvo_core::http::body::res::ResBody>,salvo_utils::rt::tokio_io::TokioIo<enum2$<tokio_util::either::Either<
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\proto\h1\dispatch.rs:144
  45: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<salvo_core::service::HyperHan
dler,hyper::body::incoming::Incoming>,enum2$<salvo_core::http::body::res::ResBody>,salvo_utils::rt::tokio_io::TokioIo<enum2$<tokio_util::either::Either<
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\proto\h1\dispatch.rs:123
  46: hyper::proto::h1::dispatch::impl$1::poll<hyper::proto::h1::dispatch::Server<salvo_core::service::HyperH
andler,hyper::body::incoming::Incoming>,enum2$<salvo_core::http::body::res::ResBody>,salvo_utils::rt::tokio_io::TokioIo<enum2$<tokio_util::either::Eithe
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\proto\h1\dispatch.rs:438
  47: hyper::server::conn::http1::upgrades::impl$1::poll<salvo_utils::rt::tokio_io::TokioIo<enum2$<tokio_util
::either::Either<salvo_core::conn::proto::ClosingInactiveConnection<salvo_core::conn::proto::Rewind<tokio::net::tcp::stream::TcpStream> >,salvo_core::co
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\hyper-1.0.0-rc.4\src\server\conn\http1.rs:440
  48: core::future::future::impl$0::poll<hyper::server::conn::http1::upgrades::UpgradeableConnection<salvo_ut
ils::rt::tokio_io::TokioIo<enum2$<tokio_util::either::Either<salvo_core::conn::proto::ClosingInactiveConnection<salvo_core::conn::proto::Rewind<tokio::n
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:113        
  49: salvo_core::conn::proto::impl$0::serve_connection::async_fn$0::closure$1<tokio::net::tcp::stream::TcpStream,salvo_core::service::HyperHandler,enum2$<salvo_core::http::body::res::ResBody> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\macros\select.rs:524
  50: tokio::future::poll_fn::impl$1::poll<enum2$<salvo_core::conn::proto::impl$0::serve_connection::async_fn
$0::__tokio_select_util::Out<enum2$<core::result::Result<tuple$<>,hyper::error::Error> >,tuple$<>,tuple$<> > >,salvo_core::conn::proto::impl$0::serve_co
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\future\poll_fn.rs:58
  51: salvo_core::conn::proto::impl$0::serve_connection::async_fn$0<tokio::net::tcp::stream::TcpStream,salvo_core::service::HyperHandler,enum2$<salvo_core::http::body::res::ResBody> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\conn\proto.rs:101
  52: salvo_core::conn::tcp::impl$3::serve::async_block$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\conn\tcp.rs:143
  53: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<>,std::io::error::Error> > > >,core::marker::Send>,alloc::alloc::Global> >  
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\future\future.rs:125        
  54: salvo_core::server::impl$0::try_serve_with_graceful_shutdown::async_fn$0::async_block$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<tuple$<> > >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\salvo_core-0.58.3\src\server.rs:243
  55: tokio::runtime::task::core::impl$6::poll::closure$0<enum2$<salvo_core::server::impl$0::try_serve_with_g
raceful_shutdown::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<t
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\core.rs:223
  56: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<enum2$<salvo_core::s
erver::impl$0::try_serve_with_graceful_shutdown::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_u
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\loom\std\unsafe_cell.rs:14
  57: tokio::runtime::task::core::Core<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutdown::a
sync_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<tuple$<> > > >,alloc
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\core.rs:212
  58: tokio::runtime::task::harness::poll_future::closure$0<enum2$<salvo_core::server::impl$0::try_serve_with
_graceful_shutdown::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\harness.rs:476
  59: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime:
:task::harness::poll_future::closure_env$0<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutdown::async_fn$0::async_block_env$3<salvo_core
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\panic\unwind_safe.rs:271    
  60: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::
poll_future::closure_env$0<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutdown::async_fn$0::async_block_env$3<salvo_core::conn::tcp::Tcp
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panicking.rs:504
  61: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness:
:cancel_task::closure_env$0<enum2$<salvo_admin::controller::chat_controller::handle_socket::async_fn$0::async_block_env$1>,alloc::sync::Arc<tokio::runti
  62: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSa
fe<tokio::runtime::task::harness::poll_future::closure_env$0<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutdown::async_fn$0::async_bloc
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panicking.rs:468
  63: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll
_future::closure_env$0<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutdown::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcce
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panic.rs:142
  64: tokio::runtime::task::harness::poll_future<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_s
hutdown::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<tuple$<> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\harness.rs:464
  65: tokio::runtime::task::harness::Harness<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutd
own::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<tuple$<> > > >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\harness.rs:198
  66: tokio::runtime::task::harness::Harness<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutd
own::async_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<tuple$<> > > >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\harness.rs:152
  67: tokio::runtime::task::raw::poll<enum2$<salvo_core::server::impl$0::try_serve_with_graceful_shutdown::as
ync_fn$0::async_block_env$3<salvo_core::conn::tcp::TcpAcceptor,salvo_core::service::Service,futures_util::future::pending::Pending<tuple$<> > > >,alloc:
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\raw.rs:255
  68: tokio::runtime::task::raw::RawTask::poll
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\raw.rs:200
  69: tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::H
andle,alloc::alloc::Global> >::run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle,alloc::alloc::Global> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\mod.rs:394
  70: tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\scheduler\multi_thread\worker.rs:464
  71: tokio::runtime::coop::with_budget
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\coop.rs:107
  72: tokio::runtime::coop::budget
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\coop.rs:73
  73: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\scheduler\multi_thread\worker.rs:463
  74: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\scheduler\multi_thread\worker.rs:426
  75: tokio::runtime::scheduler::multi_thread::worker::run::closure$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\scheduler\multi_thread\worker.rs:406
  76: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::multi_thread::worker::Context>::set<tok
io::runtime::scheduler::multi_thread::worker::Context,tokio::runtime::scheduler::multi_thread::worker::run::closure_env$0,tuple$<> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\macros\scoped_tls.rs:61
  77: tokio::runtime::scheduler::multi_thread::worker::run
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\scheduler\multi_thread\worker.rs:403
  78: tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure$0
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\scheduler\multi_thread\worker.rs:365
  79: tokio::runtime::blocking::task::impl$2::poll<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0,tuple$<> >
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\blocking\task.rs:42
  80: tokio::runtime::task::core::impl$6::poll::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio:
:runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\core.rs:223
  81: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<tokio::runtime::bloc
king::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0> > > >::with_mut<enum2$<tokio::runtime::task::co
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\loom\std\unsafe_cell.rs:14
  82: tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler
::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::Block
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\core.rs:212
  83: tokio::runtime::task::harness::poll_future::closure$0<tokio::runtime::blocking::task::BlockingTask<toki
o::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\harness.rs:476
  84: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime:
:task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch:
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\panic\unwind_safe.rs:271    
  85: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::
poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panicking.rs:504
  86: std::panicking::panicking
  87: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSa
fe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worke
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panicking.rs:468
  88: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll
_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,toki
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\std\src\panic.rs:142
  89: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<tokio::runtime:
:scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at D:\develop\rust\cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\tokio-1.28.1\src\runtime\task\harness.rs:464
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-12-21T08:40:45.529007Z ERROR Request{remote_addr=socket://127.0.0.1:63685 version=HTTP/1.1 method=POST path=http://localhost:8090/login}: salvo_extra::catch_panic: panic occurred error=Any { .. }
2023-12-21T08:40:45.529214Z  INFO Request{remote_addr=socket://127.0.0.1:63685 version=HTTP/1.1 method=POST p
ath=http://localhost:8090/login}: salvo_extra::logging: Response status=500 Internal Server Error duration=357.3688ms
发生panic
500错误
2023-12-21T08:40:45.670472Z  INFO Request{remote_addr=socket://127.0.0.1:63689 version=HTTP/1.1 method=GET path=http://localhost:8090/captchaImage}: salvo_extra::logging: Response status=200 OK duration=122.9113ms

**Comment by lyqgit** [comment]
本地测试，使用mapper直接写sql还是报错，升级rbatis到4.5后就可以正常访问了，这个异常没找到原因，之前也没出现过这个错误

**Comment by huangjie0515** [comment]
我更新下项目就好了很奇怪这种问题，之前好好的 突然就报错了  我顶多更新了rust版本
