### ISSUE TITLE
关于该项目在vscode下发生rust-analyzer崩溃的问题

### ISSUE THREAD

**Issue by yangbailan** [lyqgit/salvo-admin#9]
从dict、menu的路由开始加入model和mapper后，vscode的ra就开始崩溃了，无法提示、无法跳转、无法提示报错。

**Comment by lyqgit** [comment]
一开始我也是用vscode开发，但后来随着项目变大，rust-analyzer服务就无法代码提示和跳转，建议使用idea，并使用对应插件，我现在开发是用webstorm+rust插件
